#library(sqldf)
#acs<-read.csv("data.csv")
#q1<-sqldf("select pwgtp1 from acs where AGEP < 50")
#q2<-sqldf("select distinct AGEP from acs")
#url <- "http://biostat.jhsph.edu/~jleek/contact.html"
#con = url("http://biostat.jhsph.edu/~jleek/contact.html")
#htmlCode = readLines(con)
#close(con)
#h1<-nchar(htmlCode[10])
#h2<-nchar(htmlCode[20])
#h3<-nchar(htmlCode[30])
#h4<-nchar(htmlCode[100])
data<-read.fwf("data.for", skip = 4, widths = c(15,4,9,4,9,4,9,4,4))
s<-sum(data[6])